### ISSUE TITLE
Fix: admins want to use enters, not <br>

### ISSUE THREAD

**Issue by artofkot** [artofkot/evarist#5]
Admins, while creating content_blocks, have to type \<br\> for new line. It is easily fixed by something like
> div.content_block { white-space: pre-wrap }

and then admins can just use enter. But then all old content_blocks will be ruined. So the issue is how to fix it, not ruining older content_blocks.

**Comment by adeel** [comment]
The solution I usually use for this problem is to simply replace "\n" with "<br>" each time you render the text to HTML.  Not familiar with the context of course, but maybe this works in your case?

**Comment by artofkot** [comment]
That works, yep, but the main issue here is to have older content_blocks (problems) not ruined. The thing is we parsed them (existing problems in problem_sets) from other sources, and they have some dirty stuff like two \n in a row. So essentially the task is to fix this problem, and then go over all older problems and fix what went wrong. Or to make changes active only for newer problems (content_blocks)

Btw, why you don't use this?
>div.content_block { white-space: pre-wrap }

**Comment by adeel** [comment]
Ok, I misunderstood the problem.  Also I come from a time when there was no `white-spac'" in CSS, so I didn't know this accomplished the same thing :)

Probably then the best approach is to write some scripts that clean up the old problems (like replace \n\n by \n and so on, and whatever else is necessary).  Or will this be a lot of work?

**Comment by adeel** [comment]
(or maybe I just didn't know about the pre-wrap thing, I'm not sure :)

**Comment by artofkot** [comment]
Yep, deleting all \n, then changing <br> to \n, then replacing all multiple backspaces by one backspace, and then going over all problems to see if they are ruined or not seems good.

**Comment by antropophob** [comment]
Some questions:
1. "deleting all \n" and "changing all <br> to \n" - I think this clauses contradict each other. What should be done?
2. "replacing all multiple backspaces by one backspace" - what is "multiple backspaces"? May be spaces?
3. What actions should be performed on DB and what on content_block input form?

**Comment by artofkot** [comment]
What I wrote is sort of an algorithm, so if you do it step by step it should work.
1. First delete all \n (when there are <br>'s), and then change all <br> to \n, and then not delete new \n's.
2. I meant "spaces" instead of "backspaces", sorry.
3.  1,2,4,5 - these should be done on DB (content_blocks to be precise), 3 (pre-wrap property) should be added to div's that display content_blocks.

**Comment by antropophob** [comment]
Code for updating database:
'''
var bulk = db.content_block.initializeOrderedBulkOp();
var count = 0;

db.content_block.find().forEach(function(doc) {
    //print("Before: "+doc.text);
    var replaced=doc.text.replace(/\r\n/g, '').replace(/\n/g,'').replace(/<br\/>/g,'\r\n').replace(/<br>/g,'\r\n').replace(/  +/g, ' ');
    
    bulk.find({ '_id': doc._id }).update({
    '$set': { 'text': replaced }
    });
    count++;
    if(count % 200 === 0) {
        bulk.execute();
        bulk = db.content_block.initializeOrderedBulkOp();
    }

    //print("After: "+replaced);
}); 
bulk.execute();
'''

**Comment by artofkot** [comment]
solevd by these things inserted in code of antropophob:
1step: replace(/\r\n/g,' ').replace(/\n/g,' ').replace(/<br\/>/g,'\r\n').replace(/<br>/g,'\r\n').replace(/ +/g,' ')
2step: replace(/ +/g, ' ')
3step: replace(/\n\s+/g, '\n')
